name = "BioSequenceGraphs"
uuid = "3aa97884-90e5-11e8-2134-af657ec4f203"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"

[compat]
BioSequences = "1.1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
